# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS


TWITTER_KEY: 7p636GnmmnM1zpiSJeEQ
TWITTER_SECRET: mHCibDbfRtvELZ5OsXavz8PsHoGywpnuJhNwVNrs5U
FACEBOOK_APP_ID: 1406782849559005
FACEBOOK_SECRET: e227d91823d06e9c7cba9ad7130bd3d9
